# pizza-config-repo/auth-service.yml

server:
  port: 8081 # Domyślny port dla tego serwisu

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/auth_db # Nazwa kontenera dockerowego i bazy danych
    username: postgres
    password: password # Hasło, które ustawimy w docker-compose
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # W środowisku deweloperskim 'update' jest OK
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

# Własna konfiguracja dla JWT
jwt:
  secret: "BardzoTajnyKluczKtoryPowinienBycDluuuuuuuuuugi" # Zmieńcie to na coś swojego