server:
  port: 8080 # Bramka będzie działać na porcie 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Przykładowa trasa do serwisu autoryzacji (dodamy go później)
        # Na razie ta trasa nie będzie działać, ale jest gotowa
        - id: auth-service
          uri: lb://auth-service # małe litery
          predicates:
            - Path=/api/auth/**
